# Generated by Django 5.0.6 on 2025-08-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('-created_at',)},
        ),
    ]
