# Generated by Django 5.0.6 on 2025-08-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrolment', 'New enrolment'), ('new_material', 'New material'), ('removed', 'Removed from course')], max_length=20),
        ),
    ]
